image: alpine:latest

stages:
  - lint
  - validate
  - duplicate gpu check
  - unit test
  - build
  
# Cache modules in between jobs
cache:
  key: 
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - apk add --update npm
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: lint
  when: always

  script:
    #- apk add --update npm
    #- npm install
    - npm run lint:ci

validate:
  stage: validate
  when: always
  allow_failure: true
  script:
    #- apk add --update npm
    #- npm install
    - npm run test:validate

duplicate gpu check:
  stage: duplicate gpu check
  when: always
  script:
    #- apk add --update npm
    #- npm install
    - npm run test:CheckDuplicateGPU

unit test:
  stage: unit test
  when: always

  script:
    #- apk add --update npm
    #- npm install
    - npm run test:ci

build:
  stage: build

  script:
    #- apk add --update npm
    #- npm install
    - npm run build

  artifacts:
    when: always
    paths:
      - dist/
    reports:
      junit:
        - junit.xml
