image: alpine:latest

stages:
  - lint
  - validate
  - duplicate gpu check
  - unit test
  - build
  
# Cache modules in between jobs
cache:
  key: 
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - apk add --update npm
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: lint
  when: always

  script:
    #- apk add --update npm
    #- npm install
    - npm run lint:ci

duplicate gpu check:
  stage: duplicate gpu check
  when: always
  script:
    #- apk add --update npm
    #- npm install
    - npm run test:CheckDuplicateGPU

validate:
  stage: validate
  when: always
  allow_failure: true
  script:
    #- apk add --update npm
    #- npm install
    - npm run test:validate
  artifacts:
    when: always
    name: "Javascript Plugins"
    paths:
      - Plugins/**/*.js
      - Plugins/**/*.qml
    exclude:
      - "Plugins/**/*.test.js"
      - "Plugins/*.js"

unit test:
  stage: unit test
  when: always

  script:
    #- apk add --update npm
    #- npm install
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

# build:
#   stage: build
#   allow_failure: true # User Props will always throw errors in TS.

#   script:
#     #- apk add --update npm
#     #- npm install
#     - npm run build

#   artifacts:
#     when: always
#     name: "Javascript Plugins"
#     paths:
#       - dist/**/*.js
#     reports:
#       junit:
#         - junit.xml
