image: alpine:latest

stages:
  - lint
  - test

eslint:
  stage: lint

  script:
    - apk add --update npm
    - npm install
    - npm run lint:ci

validate:
  stage: test
  
  script:
    - apk add --update npm
    - npm install
    - npm run test:loadable